/**
 * RuleEngine — Generic Business Rules DSL
 *
 * Transforms structured rule definitions into Express middleware,
 * route guards, and database logic for ANY exam problem.
 *
 * Rules are NOT exam-specific. They work for:
 *   Voting/Elections, Library, Payroll, Clinic, Inventory, Students, etc.
 *
 * Rule types:
 *   preCheck   — Check condition before INSERT/UPDATE/DELETE
 *   postAction — UPDATE another table after INSERT/UPDATE/DELETE
 *   limitCheck — Prevent exceeding a limit per group
 *   computed   — SQL computation column for reports
 *   rank       — Ranking/window function for reports
 *
 * Usage:
 *   const rules = new RuleEngine(schemaRegistry);
 *   const middlewareCode = rules.generateMiddleware([
 *     { type: 'preCheck', ... },
 *     { type: 'limitCheck', ... }
 *   ]);
 */
class RuleEngine {
    constructor(schemaRegistry) {
        this.schemaRegistry = schemaRegistry;
    }

    /**
     * Generate Express middleware + route guards from an array of rule definitions.
     * @param {Array} rules - Array of rule definition objects
     * @param {Array} routes - Array of route configs { method, path, params, table }
     * @returns {string} Generated JavaScript code
     */
    generateAll(rules, routes) {
        if (!rules || rules.length === 0) {
            return '// No business rules defined\n';
        }

        let code = '';
        code += '// ============================================================\n';
        code += '// Business Rules — auto-generated by RuleEngine\n';
        code += '// Validates ALL data operations against defined business rules\n';
        code += '// ============================================================\n\n';

        // Group rules by type
        const preChecks = rules.filter(r => r.type === 'preCheck');
        const postActions = rules.filter(r => r.type === 'postAction');
        const limitChecks = rules.filter(r => r.type === 'limitCheck');

        // Generate validation middleware
        if (preChecks.length > 0 || limitChecks.length > 0) {
            code += this._generateValidationMiddleware(preChecks, limitChecks);
            code += '\n\n';
        }

        // Generate post-action triggers
        if (postActions.length > 0) {
            code += this._generatePostActions(postActions);
            code += '\n\n';
        }

        // Generate route guards (apply validation to specific routes)
        if (routes && routes.length > 0 && (preChecks.length > 0 || limitChecks.length > 0)) {
            code += this._generateRouteGuards(routes, preChecks, limitChecks);
            code += '\n\n';
        }

        code += '// ============================================================\n';
        code += '// End of Business Rules\n';
        code += '// ============================================================\n';

        return code;
    }

    /**
     * Generate a SQL query with computed columns for reports.
     * @param {Array} baseColumns - Array of { table, field, aggregate }
     * @param {Array} computedColumns - Array of { name, expression, type }
     * @param {Array} rankColumns - Array of { name, partitionTable, partitionField, orderTable, orderField, orderDir }
     * @param {Array} filters, sortBy, limit, groupBy, having, distinct, joinType
     * @returns {string} SQL query string
     */
    generateReportSql(baseColumns, computedColumns, rankColumns, filters, sortBy, limit, groupBy, having, distinct, joinType) {
        const { QueryGenerator } = require('./queryGenerator');
        const qg = new QueryGenerator(this.schemaRegistry);

        // Use the queryGenerator's generateReportSql for consistency
        // This delegates to the shared implementation in QueryGenerator to avoid duplication
        return qg.generateReportSql(baseColumns, computedColumns, filters, sortBy, limit, groupBy, having, distinct, joinType);
    }

    /**
     * Generate a complete report HTML page with computed columns, percentages, and rankings.
     * @param {string} reportName - Name for the report
     * @param {Array} displayColumns - What columns to display { label, field, format, highlight }
     * @returns {string} Complete HTML page
     */
    generateReportHtml(reportName, displayColumns) {
        const displayName = reportName.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
        const apiRoute = `/api/${reportName}`;

        // Build table headers from display columns
        const headers = displayColumns.map(col => {
            return `            <th>${col.label || col.field.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</th>`;
        }).join('\n');

        // Build highlighted columns (for rank winners, top scorers, etc.)
        const highlightCols = displayColumns
            .filter(col => col.highlight)
            .map(col => `"${col.field}"`)
            .join(', ');

        // Detect if there's a rank column for special winner styling
        const hasRank = displayColumns.some(c => c.field === 'rank');

        let html = '';
        html += `<!-- ========= ${displayName} Report ========= -->\n`;
        html += `// SAVE THIS AS: ${reportName}.html (place in your public/ folder)\n`;
        html += `// ========================================= -->\n\n`;
        html += '<!DOCTYPE html>\n';
        html += '<html lang="en">\n';
        html += '<head>\n';
        html += '  <meta charset="UTF-8">\n';
        html += '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
        html += `  <title>${displayName}</title>\n`;
        html += '  <script src="auth.js"></script>\n';
        html += '  <script>redirectIfNotAuthenticated();</script>\n';
        html += '  <style>\n';
        html += '    * { margin: 0; padding: 0; box-sizing: border-box; }\n';
        html += '    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #f0f2f5; padding: 20px; }\n';
        html += '    .container { max-width: 960px; margin: 0 auto; }\n';
        html += '    h1 { color: #333; margin-bottom: 20px; font-size: 24px; }\n';
        html += '    .nav-bar { background: #0078d4; padding: 12px 20px; border-radius: 8px; margin-bottom: 20px; display: flex; gap: 16px; }\n';
        html += '    .nav-bar a { color: #fff; text-decoration: none; font-size: 14px; padding: 4px 8px; border-radius: 4px; }\n';
        html += '    .nav-bar a:hover { background: rgba(255,255,255,0.15); }\n';
        html += '    table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }\n';
        html += '    th { background: #0078d4; color: #fff; padding: 12px 16px; text-align: left; font-size: 13px; font-weight: 600; }\n';
        html += '    td { padding: 10px 16px; border-bottom: 1px solid #eee; font-size: 13px; color: #333; }\n';
        html += '    tr:last-child td { border-bottom: none; }\n';
        html += '    tr:nth-child(even) { background: #f8f9fa; }\n';
        html += '    tr:hover { background: #e8f0fe; }\n';
        html += '    .total-row { background: #e8e8e8 !important; font-weight: 600; }\n';
        html += '    .total-row td { border-top: 2px solid #0078d4; }\n';
        html += '    .winner-row { background: #fff8e1 !important; }\n';
        html += '    .winner-row td:first-child::before { content: "🏆 "; }\n';
        html += '    .percent-bar { display: inline-block; height: 8px; border-radius: 4px; background: #4caf50; margin-right: 6px; vertical-align: middle; }\n';
        html += '    .rank-badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }\n';
        html += '    .rank-1 { background: #ffd700; color: #333; }\n';
        html += '    .rank-2 { background: #c0c0c0; color: #333; }\n';
        html += '    .rank-3 { background: #cd7f32; color: #fff; }\n';
        html += '    .rank-default { background: #e0e0e0; color: #666; }\n';
        html += '    .loading { text-align: center; padding: 40px; color: #888; font-size: 14px; }\n';
        html += '    .error { color: #d32f2f; padding: 16px; background: #ffebee; border-radius: 8px; }\n';
        html += '    @media print { .nav-bar { display: none; } body { padding: 0; } }\n';
        html += '  </style>\n';
        html += '</head>\n';
        html += '<body>\n';
        html += '  <div class="nav-bar">\n';
        html += '    <a href="/dashboard.html">Dashboard</a>\n';
        html += '    <a href="/login.html" onclick="logout()" style="margin-left:auto;">Logout</a>\n';
        html += '  </div>\n';
        html += '  <div class="container">\n';
        html += `    <h1>${displayName}</h1>\n`;
        html += '    <div id="reportContent">\n';
        html += '      <div class="loading">Loading report data...</div>\n';
        html += '    </div>\n';
        html += '  </div>\n';
        html += '  <script>\n';

        // Generate the data-fetching and rendering JS
        html += `    const API = '${apiRoute}';\n\n`;
        html += '    async function loadReport() {\n';
        html += '      const container = document.getElementById(\'reportContent\');\n';
        html += '      try {\n';
        html += '        const res = await authFetch(API);\n';
        html += '        if (!res.ok) throw new Error(\'Failed to load report\');\n';
        html += '        const data = await res.json();\n\n';

        html += '        if (!data || data.length === 0) {\n';
        html += '          container.innerHTML = \'<p style="text-align:center;color:#888;padding:40px;">No data available.</p>\';\n';
        html += '          return;\n';
        html += '        }\n\n';

        html += '        let html = \'<table><thead><tr>\\n\';\n';

        // Headers
        for (const col of displayColumns) {
            const label = col.label || col.field.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
            html += `        html += '            <th>${label}</th>\\n';\n`;
        }
        html += "        html += '</tr></thead><tbody>\\n';\n\n";

        html += '        data.forEach(function(row, idx) {\n';
        html += '          let cls = "";\n';
        if (hasRank) {
            html += '          if (row.rank === 1) cls = "winner-row";\n';
        }
        html += '          html += \'<tr class="\' + cls + \'">\';\n';

        // Render each column
        for (const col of displayColumns) {
            if (col.format === 'percentage') {
                html += `          html += '<td>' + (row.${col.field} != null ? Number(row.${col.field}).toFixed(2) + '%' : '0%') + '</td>';\n`;
            } else if (col.format === 'rank') {
                html += `          var rankClass = 'rank-default';\n`;
                html += `          if (row.${col.field} === 1) rankClass = 'rank-1';\n`;
                html += `          else if (row.${col.field} === 2) rankClass = 'rank-2';\n`;
                html += `          else if (row.${col.field} === 3) rankClass = 'rank-3';\n`;
                html += `          html += '<td><span class="rank-badge ' + rankClass + '">#' + row.${col.field} + '</span></td>';\n`;
            } else if (col.format === 'currency') {
                html += `          html += '<td>' + (row.${col.field} != null ? '₱' + Number(row.${col.field}).toFixed(2) : '₱0.00') + '</td>';\n`;
            } else if (col.format === 'boolean') {
                html += `          html += '<td>' + (row.${col.field} ? '✓ Yes' : '✗ No') + '</td>';\n`;
            } else if (col.format === 'progress') {
                html += `          var pct = Number(row.${col.field}) || 0;\n`;
                html += `          html += '<td><div style="display:flex;align-items:center;"><span class="percent-bar" style="width:' + Math.min(pct, 100) + 'px;"></span>' + pct.toFixed(1) + '%</div></td>';\n`;
            } else {
                html += `          html += '<td>' + (row.${col.field} != null ? row.${col.field} : '') + '</td>';\n`;
            }
        }

        html += '          html += \'</tr>\';\n';
        html += '        });\n\n';
        html += "        html += '</tbody></table>\\n';\n";
        html += '        container.innerHTML = html;\n';
        html += '      } catch (err) {\n';
        html += '        container.innerHTML = \'<div class="error">\' + err.message + \'</div>\';\n';
        html += '      }\n';
        html += '    }\n\n';
        html += '    loadReport();\n';
        html += '  </script>\n';
        html += '</body>\n';
        html += '</html>\n';

        return html;
    }

    /**
     * Generate Express server route for a report with computed columns.
     * @param {string} reportName
     * @param {Array} baseColumns
     * @param {Array} computedColumns
     * @param {Array} rankColumns
     * @param {Array} filters, sortBy, limit, groupBy, having, distinct, joinType
     * @returns {string} Server route code
     */
    generateReportServer(reportName, baseColumns, computedColumns, rankColumns, filters, sortBy, limit, groupBy, having, distinct, joinType) {
        const sql = this.generateReportSql(baseColumns, computedColumns, rankColumns, filters, sortBy, limit, groupBy, having, distinct, joinType);
        const route = `/api/${reportName}`;
        const varName = `report${reportName.charAt(0).toUpperCase() + reportName.slice(1)}`;

        let code = '';
        code += '// --- Report: ' + reportName + ' ---\n';
        // Escape SQL for template literal
        const escapedSql = sql.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
        code += 'const ' + varName + 'Sql = `' + escapedSql + '`;\n\n';
        code += "app.get('" + route + "', authenticate, (req, res) => {\n";
        code += '  try {\n';
        code += '    const rows = db.prepare(' + varName + 'Sql).all();\n';
        code += '    res.json(rows);\n';
        code += '  } catch (err) {\n';
        code += '    res.status(500).json({ error: err.message });\n';
        code += '  }\n';
        code += '});\n';
        return code;
    }

    // ======================= Internal Helpers =======================

    /**
     * Generate validation middleware from preCheck and limitCheck rules.
     */
    _generateValidationMiddleware(preChecks, limitChecks) {
        let code = '';
        code += '// --- Business Rules: Validation Middleware ---\n';
        code += "// Apply to routes: app.use('/api/someRoute', validateBusinessRules, handler)\n\n";

        code += 'function validateBusinessRules(req, res, next) {\n';
        code += '  try {\n';
        code += '    const errors = [];\n\n';

        for (let i = 0; i < preChecks.length; i++) {
            const rule = preChecks[i];
            const msg = rule.errorMessage || `Business rule violation: ${rule.checkTable}.${rule.checkField} check failed`;

            code += `    // Rule ${i + 1}: ${msg}\n`;

            // Generate the appropriate check based on the rule
            if (rule.operator === '=' || rule.operator === '!=') {
                const val = this._quoteSqlValue(rule.checkValue);
                const identityField = this._inferIdentityField(rule.checkTable);
                code += `    const row${i} = db.prepare(\`SELECT ${rule.checkField} FROM ${rule.checkTable} WHERE ${identityField} = ?\`).get(req.body.${identityField});\n`;
                if (rule.operator === '=') {
                    code += `    if (!row${i} || String(row${i}.${rule.checkField}) !== String(${val})) {\n`;
                } else {
                    code += `    if (row${i} && String(row${i}.${rule.checkField}) === String(${val})) {\n`;
                }
                code += `      errors.push('${msg.replace(/'/g, "\\'")}');\n`;
                code += '    }\n\n';
            } else if (rule.operator === 'EXISTS') {
                // Check if a record exists that satisfies a condition
                const condition = rule.condition || `req.body.${rule.field} = ${rule.checkTable}.${rule.checkField}`;
                code += `    const exists${i} = db.prepare(\`SELECT 1 FROM ${rule.checkTable} WHERE ${condition}\`).get();\n`;
                code += `    if (!exists${i}) {\n`;
                code += `      errors.push('${msg.replace(/'/g, "\\'")}');\n`;
                code += '    }\n\n';
            }
        }

        // Limit checks
        for (let i = 0; i < limitChecks.length; i++) {
            const rule = limitChecks[i];
            const msg = rule.errorMessage || `Cannot exceed ${rule.limitField} limit`;

            code += `    // Limit ${i + 1}: ${msg}\n`;
            code += `    const count${i} = db.prepare(\`SELECT COUNT(*) as cnt FROM ${rule.targetTable} WHERE ${rule.groupField} = ?\`).get(req.body.${rule.groupField});\n`;
            const limitPK = this._getPK(rule.limitTable);
            code += `    const limit${i} = db.prepare(\`SELECT ${rule.limitField} FROM ${rule.limitTable} WHERE ${limitPK} = ?\`).get(req.body.${rule.groupField});\n`;
            code += `    if (count${i} && limit${i} && count${i}.cnt >= limit${i}.${rule.limitField}) {\n`;
            code += `      errors.push('${msg.replace(/'/g, "\\'")}');\n`;
            code += '    }\n\n';
        }

        code += '    if (errors.length > 0) {\n';
        code += "      return res.status(403).json({ error: errors.join('; ') });\n";
        code += '    }\n';
        code += '    next();\n';
        code += '  } catch (err) {\n';
        code += '    res.status(500).json({ error: err.message });\n';
        code += '  }\n';
        code += '}\n';

        return code;
    }

    /**
     * Generate post-action triggers (UPDATE after INSERT, etc.)
     */
    _generatePostActions(postActions) {
        let code = '';
        code += '// --- Business Rules: Post-Action Triggers ---\n';
        code += '// Call these AFTER a successful INSERT/UPDATE/DELETE\n\n';

        for (let i = 0; i < postActions.length; i++) {
            const rule = postActions[i];
            code += `async function postAction${i}(req, res, next) {\n`;
            code += '  try {\n';

            if (rule.action === 'INSERT') {
                code += `    // After INSERT into ${rule.targetTable}, set ${rule.setTable}.${rule.setField} = ${rule.setValue}\n`;
                code += `    db.prepare(\`UPDATE ${rule.setTable} SET ${rule.setField} = ${rule.setValue} WHERE ${rule.whereField} = ?\`).run(req.body.${rule.whereSourceField});\n`;
            } else if (rule.action === 'DELETE' || rule.action === 'DEACTIVATE') {
                code += `    // After ${rule.action} on ${rule.targetTable}, update ${rule.setTable}\n`;
                code += `    db.prepare(\`UPDATE ${rule.setTable} SET ${rule.setField} = ${rule.setValue} WHERE ${rule.whereField} = ?\`).run(req.body.${rule.whereSourceField});\n`;
            }

            code += '  } catch (err) {\n';
            code += "    console.error('Post-action error:', err.message);\n";
            code += '  }\n';
            code += '  next();\n';
            code += '}\n\n';
        }

        return code;
    }

    /**
     * Generate route guard middleware that applies rules to specific routes.
     */
    _generateRouteGuards(routes, preChecks, limitChecks) {
        let code = '';
        code += '// --- Business Rules: Route-Specific Guards ---\n';
        code += '// Apply validateBusinessRules to protected routes\n\n';

        for (const route of routes) {
            const method = (route.method || 'POST').toLowerCase();
            const path = route.path || `/api/${route.table.toLowerCase()}`;
            code += `// Protect: ${method.toUpperCase()} ${path}\n`;
            code += `// Replace your existing route with:\n`;
            code += `// app.${method}('${path}', validateBusinessRules, async (req, res) => { ... });\n\n`;
        }

        return code;
    }

    /**
     * Expand a computed column expression into SQL.
     * Supports: percentage, runningTotal, rank, formula
     */
    _expandComputedExpression(expression, column) {
        if (expression === 'percentage') {
            // COUNT / SUM OVER for percentage of total
            const countExpr = column.aggregate
                ? `${column.aggregate.toUpperCase()}(${column.sourceTable}.${column.sourceField})`
                : `COUNT(${column.sourceTable}.${column.sourceField})`;
            const totalExpr = column.partitionField
                ? `SUM(${countExpr}) OVER (PARTITION BY ${column.partitionTable}.${column.partitionField})`
                : `SUM(${countExpr}) OVER ()`;
            return `ROUND(CAST(${countExpr} AS REAL) / NULLIF(${totalExpr}, 0) * 100, 2)`;
        }

        if (expression === 'runningTotal') {
            const orderBy = column.orderField
                ? `ORDER BY ${column.orderTable}.${column.orderField}`
                : '';
            const partitionBy = column.partitionField
                ? `PARTITION BY ${column.partitionTable}.${column.partitionField} `
                : '';
            return `SUM(${column.sourceTable}.${column.sourceField}) OVER (${partitionBy}${orderBy})`;
        }

        if (expression === 'rank') {
            const orderExpr = `${column.orderTable}.${column.orderField} ${column.orderDir || 'DESC'}`;
            const partitionExpr = column.partitionField
                ? `PARTITION BY ${column.partitionTable}.${column.partitionField} `
                : '';
            const func = column.rankFunction || 'DENSE_RANK';
            return `${func}() OVER (${partitionExpr}ORDER BY ${orderExpr})`;
        }

        // Custom formula — return as-is
        return expression;
    }

    /**
     * Resolve JOINs between tables using FK relationships.
     */
    _resolveJoins(tableNames, joinType) {
        const joinT = joinType || 'LEFT';
        const tableObjs = tableNames
            .map(t => ({ name: t, table: this.schemaRegistry.getTable(t) }))
            .filter(t => t.table);

        // Collect outgoing FK references
        const outgoingFKs = {};
        for (const tObj of tableObjs) {
            const fks = [];
            for (const f of (tObj.table.fields || [])) {
                if (f.fk && tableNames.includes(f.fk.table)) {
                    fks.push({ fromField: f.name, targetTable: f.fk.table, targetField: f.fk.field });
                }
            }
            outgoingFKs[tObj.name] = fks;
        }

        // Collect incoming FK references
        const incomingFKs = {};
        for (const tName of tableNames) {
            incomingFKs[tName] = [];
            for (const [otherName, fks] of Object.entries(outgoingFKs)) {
                for (const fk of fks) {
                    if (fk.targetTable === tName) {
                        incomingFKs[tName].push({ fromTable: otherName, fromField: fk.fromField, targetField: fk.targetField });
                    }
                }
            }
        }

        // Main table = the one with the most outgoing FKs
        let mainTable = tableNames[0];
        let maxOutgoing = 0;
        for (const [tName, fks] of Object.entries(outgoingFKs)) {
            if (fks.length > maxOutgoing) {
                maxOutgoing = fks.length;
                mainTable = tName;
            }
        }

        const joins = [];
        const joinedTables = new Set([mainTable]);
        const queue = [mainTable];

        while (queue.length > 0) {
            const currentTable = queue.shift();
            // Outgoing FKs
            for (const fk of (outgoingFKs[currentTable] || [])) {
                if (!joinedTables.has(fk.targetTable)) {
                    joins.push(`${joinT} JOIN ${fk.targetTable} ON ${currentTable}.${fk.fromField} = ${fk.targetTable}.${fk.targetField}`);
                    joinedTables.add(fk.targetTable);
                    queue.push(fk.targetTable);
                }
            }
            // Incoming FKs
            for (const fk of (incomingFKs[currentTable] || [])) {
                if (!joinedTables.has(fk.fromTable)) {
                    joins.push(`${joinT} JOIN ${fk.fromTable} ON ${currentTable}.${fk.targetField} = ${fk.fromTable}.${fk.fromField}`);
                    joinedTables.add(fk.fromTable);
                    queue.push(fk.fromTable);
                }
            }
        }

        // CROSS JOIN any remaining tables
        for (const tName of tableNames) {
            if (!joinedTables.has(tName)) {
                joins.push(`CROSS JOIN ${tName}`);
                joinedTables.add(tName);
            }
        }

        return { mainTable, joins };
    }

    _inferIdentityField(tableName) {
        const table = this.schemaRegistry.getTable(tableName);
        if (!table || !table.fields) return null;
        // Look for common identity patterns
        for (const f of table.fields) {
            const lower = f.name.toLowerCase();
            if (lower === 'id' || lower.endsWith('id') || lower.endsWith('no')) {
                return f.name;
            }
        }
        // Fallback to first non-PK field
        const firstNonPK = table.fields.find(f => !f.pk);
        return firstNonPK ? firstNonPK.name : (table.fields[0] ? table.fields[0].name : 'id');
    }

    _getPK(tableName) {
        const table = this.schemaRegistry.getTable(tableName);
        if (!table) return 'id';
        const pk = table.fields.find(f => f.pk);
        return pk ? pk.name : (table.fields[0]?.name || 'id');
    }

    _quoteSqlValue(val) {
        if (val === null || val === undefined) return 'NULL';
        const str = String(val);
        if (/^-?\d+(\.\d+)?$/.test(str)) return str;
        return "'" + str.replace(/'/g, "''") + "'";
    }
}

module.exports = { RuleEngine };
